apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geth-bootnode
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: geth
        type: bootnode
    spec:
      containers:
        - name: geth-bootnode
          image: ali92hm/node:geth
          command: [bootnode, -addr, "0.0.0.0:30303", -nodekeyhex, $(BOOTNODE_KEY)]
          imagePullPolicy: IfNotPresent
          env:
            - name: BOOTNODE_KEY
              valueFrom:
                secretKeyRef:
                  name: chain-secrets
                  key: bootnode-key
          ports:
            - name: geth-tcp
              containerPort: 30303
              protocol: TCP
            - name: geth-udp
              containerPort: 30303
              protocol: UDP
