apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geth-miner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: geth
        type: miner
    spec:
      containers:
        - name: geth-miner
          image: ali92hm/geth:k8s
          args: ["--mine", "--etherbase", "0x6ca393ad5e8c30e14f40c91af76bf7d79ebcbce2"]
          imagePullPolicy: Always
          # imagePullPolicy: IfNotPresent
          env:
          - name: BOOTNODE_KEY
            valueFrom:
              secretKeyRef:
                name: chain-secrets
                key: bootnode-key
          - name: NETWORK_ID
            valueFrom:
              secretKeyRef:
                name: chain-secrets
                key: network-id
          ports:
            - name: geth-tcp
              containerPort: 30303
              protocol: TCP
            - name: geth-udp
              containerPort: 30303
              protocol: UDP
