apiVersion: v1
kind: Service
metadata:
  name: bootnode-svc
  labels:
    app: geth
    type: bootnode
spec:
  selector:
    app: geth
    type: bootnode
  ports:
    - name: geth-tcp
      port: 30303
      targetPort: 30303
      protocol: TCP
    - name: geth-udp
      port: 30303
      targetPort: 30303
      protocol: UDP
