apiVersion: v1
kind: Pod
metadata:
  name: geth-tx-pod
  labels:
    app: geth
    type: tx-test
spec:
  containers:
    - name: geth-tx-test
      image: ali92hm/geth:k8s
      args: ["--rpc", "--rpcaddr", "0.0.0.0"]
      imagePullPolicy: Always
      # imagePullPolicy: IfNotPresent
      env:
      - name: BOOTNODE_KEY
        valueFrom:
          secretKeyRef:
            name: chain-secrets
            key: bootnode-key
      - name: NETWORK_ID
        valueFrom:
          secretKeyRef:
            name: chain-secrets
            key: network-id
      - name: GENESIS
        valueFrom:
          secretKeyRef:
            name: chain-secrets
            key: genesis
      ports:
        - name: geth-tcp
          containerPort: 30303
          protocol: TCP
        - name: geth-udp
          containerPort: 30303
          protocol: UDP
        - name: geth-rpc
          containerPort: 8545
          protocol: TCP
