apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geth-tx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: geth-tx
        app: geth
        type: tx
    spec:
      containers:
        - name: geth-tx
          image: ali92hm/geth:k8s
          args: ["--rpc", "--rpcaddr", "0.0.0.0"]
          imagePullPolicy: Always
          # imagePullPolicy: IfNotPresent
          env:
          - name: BOOTNODE_KEY
            valueFrom:
              secretKeyRef:
                name: chain-secrets
                key: bootnode-key
          - name: NETWORK_ID
            valueFrom:
              secretKeyRef:
                name: chain-secrets
                key: network-id
          - name: GENESIS
            valueFrom:
              secretKeyRef:
                name: chain-secrets
                key: genesis
          ports:
            - name: geth-tcp
              containerPort: 30303
              protocol: TCP
            - name: geth-udp
              containerPort: 30303
              protocol: UDP
            - name: geth-rpc
              containerPort: 8545
              protocol: TCP
