apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geth-tx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: geth-tx
        app: geth
        type: tx
    spec:
      containers:
        - name: geth-tx
          image: ali92hm/node:geth
          args: ["--networkid", "201708",
            "--bootnodes", "enode://3f2fd156f7826df00e6e86c49445e7a6ade873f254196e3a660af5273df74a81b228c9b5ac146331f1e402d765e1dcbf10ea685a5607a5c1e105b3f553dbb913@$(BOOTNODE_SVC_SERVICE_HOST):$(BOOTNODE_SVC_SERVICE_PORT)",
            "--rpc",
            "--rpcaddr", "0.0.0.0"]
          imagePullPolicy: Always
          env:
          - name: HEX
            value: 714eef23d30cbd12fd0b1a6cea7895fa3075fcf574066da3457a67f6e018c220
          ports:
            - name: geth-tcp
              containerPort: 30303
              protocol: TCP
            - name: geth-udp
              containerPort: 30303
              protocol: UDP
            - name: geth-rpc
              containerPort: 8545
              protocol: TCP
